### ISSUE TITLE
XMILE - yeah/nah?

### ISSUE THREAD

**Issue by benswift** [anu-act-health-covid19-support/patientpaths#1]
Looking into this XMILE thing, it looks a _bit_ abandonwarey (although that might be just because it's mature & feature-complete).

Looks like [this mob](https://github.com/SDXorg) are the ones behind it, and it _mostly_ lives in a proprietary software world (e.g. STELLA, iThink, Vensim) although there's some self-reflective stuff in [this README](https://github.com/JamesPHoughton/pysd) about the need to go where developers & data scientists actually _are_, i.e. Python.

So I think it's probably not the "fully open ecosystem" thing we're after. Thoughts, @Markopolo141 ?

**Comment by Markopolo141** [comment]
yeah, does look a bit sparse hey.
I think that getting old MOC system working xarray I something we can work on, and if we want to use xmile, we will build/think-about later

**Comment by benswift** [comment]
Yep, I think so. That's a **nah** to XMILE for now.
