### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by benswift** [anu-act-health-covid19-support/patientpaths#3]
At some stage it'd be good to at least add some testing infrastructure (even if then coverage might not be great initially). Then, we can even add a github action to run the test suite, e.g. on pushes to master or on merge requests.

@Zac-HD can you do this? Don't worry about the GH actions stuff if you haven't done that before, I can set that up. Just tell me when the testing stuff is in there.

**Comment by Zac-HD** [comment]
https://github.com/anu-act-health-covid19-support/patientpaths/actions is already set up, including testing infrastructure :smile:  Just add more in https://github.com/anu-act-health-covid19-support/patientpaths/tree/master/tests and uncomment `--cov-fail-under=100` in `tox.ini` when we want to insist on full coverage, and we'll be done!

**Comment by benswift** [comment]
Oh, well that's great---sorry I didn't actually look first 😄

**Comment by benswift** [comment]
Hey @Zac-HD I spoke to Jochen and he's keen on including a couple of types of tests.

1. Verify that the outputs against known inputs satisfy specific invariants (either specific values or certain statistical properties where appropriate). This could include obvious things like making sure that none of the clinical resources are ever over-capacity, but also things like checking that the outputs possess any statistical properties which we can prove they should have.

2. Compare the results of the new implementation against results from the old one (modulo any corrections for the bugs in the old one). It's *probably* too much hassle to get a live MATLAB instance running in GitHub actions, so the better option might be to pre-generate some files from MATLAB (I've still got it here on e.g. my linux box) and just run the tests on that known "good" data. We could even bake the data into a docker image that we use to run the test in or something.

Anyway, I think that #9 is the higher priority, but I'm just flagging this here and re-opening, because it's been put back on the todo list.

**Comment by Zac-HD** [comment]
For (1), we can absolutely test that bounds are not exceeded, no people 'go missing' in the simulation (as they did in the original), etc.  I expect that this will shake out a few bugs!  Statistical properties are actually very difficult to test though, since this is not a system which converges at all quickly.

For (2), unfortunately this is a non-starter.  Quite aside from the difficulty of compensating for upstream bugs, we'll be using a different random-number generator and that will throw the results off considerably.

**Comment by benswift** [comment]
Hey @Zac-HD yep, agree that testing invariants like "conservation of people", etc. are probably good ones to test for now.

Re: (2) yep, I realise that direct equality checks aren't what we're after. I guess the reason I said "compare" results from old vs new was thinking about whether there were some sorts of consistency checks we could do. For example, comparing the differences in the output statistics under various scenarios---e.g. what's the (average) difference in total number of excess capacity required under a specific set of `R_0`, `rho`, etc.

Partially because I haven't actually seen any confirmation yet that the new model gives results that are in the ballpark of the old one. @Markopolo141 may have done this? Either way, I think it's important to run the old vs new and see what some of the differences are (even if it doesn't make sense to turn it into a test).

**Comment by benswift** [comment]
@Zac-HD are you able to add in the basic tests you mention for (1)?
