### ISSUE TITLE
appropriate code/folder structure for inputs/outputs

### ISSUE THREAD

**Issue by benswift** [anu-act-health-covid19-support/patientpaths#6]
We need to have a think about where the "data" (in JSON files) should go.

@Zac-HD what's the most pythonic way to lay this out?

**Comment by Zac-HD** [comment]
I'd be inclined to make the input data file a required argument to the CLI, either for a single filename or for a directory with well-known input file names.  Output I guess could default to `output.json` in the current working directory, with an error if the file already exists?

This really depends on how we organise the data though, that that in turn depends on who edits it and how often.

**Comment by benswift** [comment]
Cool. Any chance you could stub that out?

**Comment by benswift** [comment]
Hey @Zac-HD any progress on this? I guess what I was thinking was:

- putting the relevant files in places (and `setup.py` config) to make it so that there will be a `patientpaths` cli tool as part of the package
- infrastructure (argparse or whatever you reckon) to handle all the arguments (and `--help` as well)

I know that we haven't _completely_ decided on the CLI args/interface, but it could be  something like:

```sh
$ patientpaths --help
Usage: patientpaths CAPACITIES_FILE PRESENTATIONS_FILE [-o OUTPUT_FILE]

  Run the clinical pathway model for a given health system capacity and predicted disease
  presentations.

Presentations file format:
  TODO

Capacities file format:
  TODO
```

Now, @Markopolo141 has the code written to re-create the original MATLAB model, but I don't think he knows exactly where to put it to make the CLI tool work as above. Can you stub it out for him?

Is there any more info you need to do this? This needs to happen before we can complete #9

**Comment by benswift** [comment]
Also, if you've got a nicer idea for what the CLI tool UX should be then I'm all ears - that was just a quick design sketch I put together when writing up this issue :)
